name: GitHub Action for building DolphinOS ISO

on: workflow_dispatch

jobs:
  build_iso:
    name: Create and build DolphinOS ISO
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged
      env:
        TZ: Europe/Madrid

    steps:
    - name: Update packages and install required dependencies for the job
      run: | 
        pacman -Syu --noconfirm --needed sudo git base-devel reflector archiso mkinitcpio-archiso squashfs-tools wget base-devel curl lftp networkmanager rsync openssh
        reflector --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
        pacman -Syu --noconfirm
    - uses: actions/checkout@v3
    - name: Set current date and hour as environment variable
      run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
    # - name: Build ISO
    #   run: |
    #     mkdir work
    #     mkdir build
    #     mkarchiso -v -w work -o build archiso
    #     rm -rf work
    # - name: Upload ISO to Sourceforge Releases
    #   run: |
    #     mkdir -p ~/.ssh
    #     ssh-keyscan -H frs.sourceforge.net > ~/.ssh/known_hosts
    #     rsync -avz -e "ssh -i ${{ secrets.SOURCEFORGE_PRIVATE_KEY }}" build/dolphinos*.iso dolphinos@frs.sourceforge.net:/home/frs/project/DolphinOS/DolphinOS
    - uses: actions/checkout@v3
      with:
        ref: nvidia
    # - name: Build NVIDIA ISO
    #   run: |
    #     rm -rf work
    #     rm -rf build
    #     mkdir work
    #     mkdir build
    #     mkarchiso -v -w work -o build archiso
    #     rm -rf work
    - name: Upload NVIDIA ISO to Sourceforge releases
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H frs.sourceforge.net > ~/.ssh/known_hosts
        eval $(ssh-agent)
        ssh-add - <<< "$SSH_KEY"
        ssh-add
        rsync -avz -e ssh archiso/profiledef.sh dolphinos@frs.sourceforge.net:/home/frs/project/dolphinos/DolphinOS-NVIDIA
      env:
        SSH_KEY: ${{ secrets.SOURCEFORGE_PRIVATE_KEY }}
    # - name: Publish Sourceforge link to releases
    #   uses: ncipollo/release-action@v1
    #   with:
    #     body: "Automatically built latest ISO\nLink: https://sourceforge.net/projects/dolphinos"
    #     tag: "DolphinOS-ISO-${{ env.NOW }}"
    #     allowUpdates: true
    #     makeLatest: true