name: GitHub Action for building DolphinOS ISO

on: workflow_dispatch

jobs:
  build_iso:
    name: Create and build DolphinOS ISO
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged
      env:
        TZ: Europe/Madrid

    steps:
    - name: Update packages and install required dependencies for the job
      run: | 
        pacman -Syu --noconfirm --needed sudo git base-devel reflector archiso mkinitcpio-archiso squashfs-tools wget base-devel curl lftp networkmanager
        reflector --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
        pacman -Syu --noconfirm
    - uses: actions/checkout@v3
    - name: Set current date and hour as environment variable
      run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
    - name: Build ISO
      run: |
        mkdir work
        mkdir build
        mkarchiso -v -w work -o build archiso
        rm -rf work
    - name: Upload ISO to releases
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: build/dolphinos*.iso
        tag: DolphinOS-ISO-${{ env.NOW }}
        prerelease: false
        overwrite: true
        body: "Automatically built latest ISO"
        make_latest: true